import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
  // Readonly<T>: TypeScript의 유틸리티 타입입니다. 타입 T의 모든 프로퍼티를 읽기 전용(read-only)으로 만듭니다.
}: Readonly<{
  // { children: React.ReactNode; }: 객체 리터럴 타입입니다. children 프로퍼티를 React.ReactNode 타입으로 정의합니다.
  children: React.ReactNode; // React.ReactNode: React에서 렌더링 가능한 모든 것(React 엘리먼트, 문자열, 숫자, boolean 등)을 나타내는 타입입니다.
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-neutral-900 text-white max-w-screen-sm mx-auto`}
      >
        {children}
      </body>
    </html>
  );
}
